//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kangaroo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kangaroo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About KangarooCare.
        /// </summary>
        internal static string lbAbout {
            get {
                return ResourceManager.GetString("lbAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        internal static string lbAbsent {
            get {
                return ResourceManager.GetString("lbAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string lbAccept {
            get {
                return ResourceManager.GetString("lbAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation.
        /// </summary>
        internal static string lbActivation {
            get {
                return ResourceManager.GetString("lbActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        internal static string lbActivationCode {
            get {
                return ResourceManager.GetString("lbActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Type.
        /// </summary>
        internal static string lbActivityType {
            get {
                return ResourceManager.GetString("lbActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lbAdd {
            get {
                return ResourceManager.GetString("lbAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        internal static string lbAddActivity {
            get {
                return ResourceManager.GetString("lbAddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Child.
        /// </summary>
        internal static string lbAddChild {
            get {
                return ResourceManager.GetString("lbAddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More.
        /// </summary>
        internal static string lbAddMore {
            get {
                return ResourceManager.GetString("lbAddMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write reply.
        /// </summary>
        internal static string lbAddReply {
            get {
                return ResourceManager.GetString("lbAddReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Report.
        /// </summary>
        internal static string lbAddReport {
            get {
                return ResourceManager.GetString("lbAddReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lbAddress {
            get {
                return ResourceManager.GetString("lbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree to the terms and conditions.
        /// </summary>
        internal static string lbAgreeTerms {
            get {
                return ResourceManager.GetString("lbAgreeTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string lbApply {
            get {
                return ResourceManager.GetString("lbApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string lbAttendance {
            get {
                return ResourceManager.GetString("lbAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee.
        /// </summary>
        internal static string lbAttended {
            get {
                return ResourceManager.GetString("lbAttended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string lbBack {
            get {
                return ResourceManager.GetString("lbBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string lbBirthDate {
            get {
                return ResourceManager.GetString("lbBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string lbCamera {
            get {
                return ResourceManager.GetString("lbCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lbCancel {
            get {
                return ResourceManager.GetString("lbCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string lbChangeLanguage {
            get {
                return ResourceManager.GetString("lbChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string lbChangePassword {
            get {
                return ResourceManager.GetString("lbChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Profile.
        /// </summary>
        internal static string lbChildData {
            get {
                return ResourceManager.GetString("lbChildData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Face.
        /// </summary>
        internal static string lbChildFace {
            get {
                return ResourceManager.GetString("lbChildFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Gallery.
        /// </summary>
        internal static string lbChildGallery {
            get {
                return ResourceManager.GetString("lbChildGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Name.
        /// </summary>
        internal static string lbChildName {
            get {
                return ResourceManager.GetString("lbChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Profile.
        /// </summary>
        internal static string lbChildProfile {
            get {
                return ResourceManager.GetString("lbChildProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Progress.
        /// </summary>
        internal static string lbChildProgress {
            get {
                return ResourceManager.GetString("lbChildProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Relationship.
        /// </summary>
        internal static string lbChildRelation {
            get {
                return ResourceManager.GetString("lbChildRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string lbCity {
            get {
                return ResourceManager.GetString("lbCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string lbClass {
            get {
                return ResourceManager.GetString("lbClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string lbClasses {
            get {
                return ResourceManager.GetString("lbClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string lbClassName {
            get {
                return ResourceManager.GetString("lbClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string lbCode {
            get {
                return ResourceManager.GetString("lbCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        internal static string lbConfirmEmail {
            get {
                return ResourceManager.GetString("lbConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string lbConfirmPassword {
            get {
                return ResourceManager.GetString("lbConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string lbContact {
            get {
                return ResourceManager.GetString("lbContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Data.
        /// </summary>
        internal static string lbContactData {
            get {
                return ResourceManager.GetString("lbContactData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Family.
        /// </summary>
        internal static string lbContactFamily {
            get {
                return ResourceManager.GetString("lbContactFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        internal static string lbContactName {
            get {
                return ResourceManager.GetString("lbContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No..
        /// </summary>
        internal static string lbContactNo {
            get {
                return ResourceManager.GetString("lbContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string lbContactNumber {
            get {
                return ResourceManager.GetString("lbContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Parent.
        /// </summary>
        internal static string lbContactParent {
            get {
                return ResourceManager.GetString("lbContactParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string lbContactUs {
            get {
                return ResourceManager.GetString("lbContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lbCountry {
            get {
                return ResourceManager.GetString("lbCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Account.
        /// </summary>
        internal static string lbCreateAccount {
            get {
                return ResourceManager.GetString("lbCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create The Daily Report.
        /// </summary>
        internal static string lbCreateReport {
            get {
                return ResourceManager.GetString("lbCreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Activities.
        /// </summary>
        internal static string lbDailyReportActivity {
            get {
                return ResourceManager.GetString("lbDailyReportActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos And Videos.
        /// </summary>
        internal static string lbDailyReportMedia {
            get {
                return ResourceManager.GetString("lbDailyReportMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Reports.
        /// </summary>
        internal static string lbDailyReports {
            get {
                return ResourceManager.GetString("lbDailyReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lbDate {
            get {
                return ResourceManager.GetString("lbDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayCare.
        /// </summary>
        internal static string lbDayCare {
            get {
                return ResourceManager.GetString("lbDayCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayCare Info..
        /// </summary>
        internal static string lbDayCareDesc {
            get {
                return ResourceManager.GetString("lbDayCareDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayCares.
        /// </summary>
        internal static string lbDayCares {
            get {
                return ResourceManager.GetString("lbDayCares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lbDelete {
            get {
                return ResourceManager.GetString("lbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc.
        /// </summary>
        internal static string lbDesc {
            get {
                return ResourceManager.GetString("lbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string lbEdit {
            get {
                return ResourceManager.GetString("lbEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact data.
        /// </summary>
        internal static string lbEmergencyContact {
            get {
                return ResourceManager.GetString("lbEmergencyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string lbEndDate {
            get {
                return ResourceManager.GetString("lbEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string lbEnter {
            get {
                return ResourceManager.GetString("lbEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your data.
        /// </summary>
        internal static string lbEnterData {
            get {
                return ResourceManager.GetString("lbEnterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Address.
        /// </summary>
        internal static string lbFatherAddress {
            get {
                return ResourceManager.GetString("lbFatherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Data.
        /// </summary>
        internal static string lbFatherData {
            get {
                return ResourceManager.GetString("lbFatherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Mobile.
        /// </summary>
        internal static string lbFatherMobile {
            get {
                return ResourceManager.GetString("lbFatherMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        internal static string lbFatherName {
            get {
                return ResourceManager.GetString("lbFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father National Id.
        /// </summary>
        internal static string lbFatherNationalId {
            get {
                return ResourceManager.GetString("lbFatherNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father National ID Image.
        /// </summary>
        internal static string lbFatherNationalIdImage {
            get {
                return ResourceManager.GetString("lbFatherNationalIdImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite DayCares.
        /// </summary>
        internal static string lbFavoriteDayCares {
            get {
                return ResourceManager.GetString("lbFavoriteDayCares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string lbFemale {
            get {
                return ResourceManager.GetString("lbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter DayCares.
        /// </summary>
        internal static string lbFilterDayCares {
            get {
                return ResourceManager.GetString("lbFilterDayCares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password ?.
        /// </summary>
        internal static string lbForgetPassword {
            get {
                return ResourceManager.GetString("lbForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        internal static string lbForgetPasswordTitle {
            get {
                return ResourceManager.GetString("lbForgetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string lbFromDate {
            get {
                return ResourceManager.GetString("lbFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        internal static string lbFromTime {
            get {
                return ResourceManager.GetString("lbFromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string lbGender {
            get {
                return ResourceManager.GetString("lbGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Notes.
        /// </summary>
        internal static string lbGeneralNotes {
            get {
                return ResourceManager.GetString("lbGeneralNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health conditions and allergies.
        /// </summary>
        internal static string lbHealthCondition {
            get {
                return ResourceManager.GetString("lbHealthCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        internal static string lbHolidays {
            get {
                return ResourceManager.GetString("lbHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Type.
        /// </summary>
        internal static string lbHolidayType {
            get {
                return ResourceManager.GetString("lbHolidayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible for daily delivering the child to home.
        /// </summary>
        internal static string lbHomeWays {
            get {
                return ResourceManager.GetString("lbHomeWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string lbImages {
            get {
                return ResourceManager.GetString("lbImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Image.
        /// </summary>
        internal static string lbImageView {
            get {
                return ResourceManager.GetString("lbImageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Activity.
        /// </summary>
        internal static string lbImportActivity {
            get {
                return ResourceManager.GetString("lbImportActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Date.
        /// </summary>
        internal static string lbInitialDate {
            get {
                return ResourceManager.GetString("lbInitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Needs ?.
        /// </summary>
        internal static string lbIsSpecialNeeds {
            get {
                return ResourceManager.GetString("lbIsSpecialNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Numbers.
        /// </summary>
        internal static string lbKidsCount {
            get {
                return ResourceManager.GetString("lbKidsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lbLogin {
            get {
                return ResourceManager.GetString("lbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your child with you  moment by moment.
        /// </summary>
        internal static string lbLoginHint {
            get {
                return ResourceManager.GetString("lbLoginHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string lbLogout {
            get {
                return ResourceManager.GetString("lbLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string lbMain {
            get {
                return ResourceManager.GetString("lbMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string lbMale {
            get {
                return ResourceManager.GetString("lbMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string lbMessage {
            get {
                return ResourceManager.GetString("lbMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Content.
        /// </summary>
        internal static string lbMessageContent {
            get {
                return ResourceManager.GetString("lbMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Details.
        /// </summary>
        internal static string lbMessageDetails {
            get {
                return ResourceManager.GetString("lbMessageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string lbMessages {
            get {
                return ResourceManager.GetString("lbMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Title.
        /// </summary>
        internal static string lbMessageTitle {
            get {
                return ResourceManager.GetString("lbMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string lbMobile {
            get {
                return ResourceManager.GetString("lbMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile (5XXXXXXXX).
        /// </summary>
        internal static string lbMobileWithHint {
            get {
                return ResourceManager.GetString("lbMobileWithHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string lbMore {
            get {
                return ResourceManager.GetString("lbMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Address.
        /// </summary>
        internal static string lbMotherAddress {
            get {
                return ResourceManager.GetString("lbMotherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Data.
        /// </summary>
        internal static string lbMotherData {
            get {
                return ResourceManager.GetString("lbMotherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Mobile.
        /// </summary>
        internal static string lbMotherMobile {
            get {
                return ResourceManager.GetString("lbMotherMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Name.
        /// </summary>
        internal static string lbMotherName {
            get {
                return ResourceManager.GetString("lbMotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother National Id.
        /// </summary>
        internal static string lbMotherNationalId {
            get {
                return ResourceManager.GetString("lbMotherNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother National ID Image.
        /// </summary>
        internal static string lbMotherNationalIdImage {
            get {
                return ResourceManager.GetString("lbMotherNationalIdImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Childern.
        /// </summary>
        internal static string lbMyChildern {
            get {
                return ResourceManager.GetString("lbMyChildern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Kids.
        /// </summary>
        internal static string lbMyChildren {
            get {
                return ResourceManager.GetString("lbMyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string lbMyProfile {
            get {
                return ResourceManager.GetString("lbMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbName {
            get {
                return ResourceManager.GetString("lbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Id.
        /// </summary>
        internal static string lbNationalId {
            get {
                return ResourceManager.GetString("lbNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string lbNewPassword {
            get {
                return ResourceManager.GetString("lbNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string lbNext {
            get {
                return ResourceManager.GetString("lbNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lbNo {
            get {
                return ResourceManager.GetString("lbNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string lbNotes {
            get {
                return ResourceManager.GetString("lbNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string lbNotifications {
            get {
                return ResourceManager.GetString("lbNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string lbNotifyUs {
            get {
                return ResourceManager.GetString("lbNotifyUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lbNutritionType {
            get {
                return ResourceManager.GetString("lbNutritionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string lbOldPassword {
            get {
                return ResourceManager.GetString("lbOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Data.
        /// </summary>
        internal static string lbParentData {
            get {
                return ResourceManager.GetString("lbParentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Mobile.
        /// </summary>
        internal static string lbParentMobile {
            get {
                return ResourceManager.GetString("lbParentMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name.
        /// </summary>
        internal static string lbParentName {
            get {
                return ResourceManager.GetString("lbParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Notifications.
        /// </summary>
        internal static string lbParentNotifications {
            get {
                return ResourceManager.GetString("lbParentNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Photo.
        /// </summary>
        internal static string lbPickPhoto {
            get {
                return ResourceManager.GetString("lbPickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Video.
        /// </summary>
        internal static string lbPickVideo {
            get {
                return ResourceManager.GetString("lbPickVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Video.
        /// </summary>
        internal static string lbPlayVideo {
            get {
                return ResourceManager.GetString("lbPlayVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string lbPoints {
            get {
                return ResourceManager.GetString("lbPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string lbPrevious {
            get {
                return ResourceManager.GetString("lbPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string lbPrivacyPolicy {
            get {
                return ResourceManager.GetString("lbPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code.
        /// </summary>
        internal static string lbPromoCode {
            get {
                return ResourceManager.GetString("lbPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string lbRegister {
            get {
                return ResourceManager.GetString("lbRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        internal static string lbRelation {
            get {
                return ResourceManager.GetString("lbRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string lbReports {
            get {
                return ResourceManager.GetString("lbReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        internal static string lbResend {
            get {
                return ResourceManager.GetString("lbResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string lbResetPassword {
            get {
                return ResourceManager.GetString("lbResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request New DayCare.
        /// </summary>
        internal static string lbRquestNewDayCare {
            get {
                return ResourceManager.GetString("lbRquestNewDayCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lbSearch {
            get {
                return ResourceManager.GetString("lbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by daycare name.
        /// </summary>
        internal static string lbSearchDayCare {
            get {
                return ResourceManager.GetString("lbSearchDayCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Keyword.
        /// </summary>
        internal static string lbSearchKeyword {
            get {
                return ResourceManager.GetString("lbSearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string lbSelectCountry {
            get {
                return ResourceManager.GetString("lbSelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string lbSend {
            get {
                return ResourceManager.GetString("lbSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string lbSender {
            get {
                return ResourceManager.GetString("lbSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lbSenderEmail {
            get {
                return ResourceManager.GetString("lbSenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name.
        /// </summary>
        internal static string lbSenderName {
            get {
                return ResourceManager.GetString("lbSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        internal static string lbSendMessage {
            get {
                return ResourceManager.GetString("lbSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Password.
        /// </summary>
        internal static string lbSendPassword {
            get {
                return ResourceManager.GetString("lbSendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Reset Code.
        /// </summary>
        internal static string lbSendResetCode {
            get {
                return ResourceManager.GetString("lbSendResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string lbSettings {
            get {
                return ResourceManager.GetString("lbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siblings Number.
        /// </summary>
        internal static string lbSiblingsNo {
            get {
                return ResourceManager.GetString("lbSiblingsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Needs.
        /// </summary>
        internal static string lbSpecialNeeds {
            get {
                return ResourceManager.GetString("lbSpecialNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string lbStartDate {
            get {
                return ResourceManager.GetString("lbStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        internal static string lbStudio {
            get {
                return ResourceManager.GetString("lbStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        internal static string lbTakePhoto {
            get {
                return ResourceManager.GetString("lbTakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lbTime {
            get {
                return ResourceManager.GetString("lbTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lbTitle {
            get {
                return ResourceManager.GetString("lbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string lbToDate {
            get {
                return ResourceManager.GetString("lbToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        internal static string lbToTime {
            get {
                return ResourceManager.GetString("lbToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message.
        /// </summary>
        internal static string lbTypeMessage {
            get {
                return ResourceManager.GetString("lbTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        internal static string lbUpdateProfile {
            get {
                return ResourceManager.GetString("lbUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photos And Videos.
        /// </summary>
        internal static string lbUploadGallery {
            get {
                return ResourceManager.GetString("lbUploadGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Child Photo.
        /// </summary>
        internal static string lbUsePhoto {
            get {
                return ResourceManager.GetString("lbUsePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data.
        /// </summary>
        internal static string lbUserData {
            get {
                return ResourceManager.GetString("lbUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string lbUserProfile {
            get {
                return ResourceManager.GetString("lbUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Child Profile.
        /// </summary>
        internal static string lbViewChildProfile {
            get {
                return ResourceManager.GetString("lbViewChildProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string lbWebSite {
            get {
                return ResourceManager.GetString("lbWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string lbWelcome {
            get {
                return ResourceManager.GetString("lbWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need To Know.
        /// </summary>
        internal static string lbWhatToKnow {
            get {
                return ResourceManager.GetString("lbWhatToKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to working Days.
        /// </summary>
        internal static string lbWorkingDays {
            get {
                return ResourceManager.GetString("lbWorkingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        internal static string lbWorkingHours {
            get {
                return ResourceManager.GetString("lbWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lbYes {
            get {
                return ResourceManager.GetString("lbYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created successfully.
        /// </summary>
        internal static string msgAccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("msgAccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activated successfully.
        /// </summary>
        internal static string msgActivationCompleted {
            get {
                return ResourceManager.GetString("msgActivationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add gallery error.
        /// </summary>
        internal static string msgAddGalleryError {
            get {
                return ResourceManager.GetString("msgAddGalleryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Added Successfully.
        /// </summary>
        internal static string msgChildAddedSuccessfully {
            get {
                return ResourceManager.GetString("msgChildAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure from delete ?.
        /// </summary>
        internal static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email error.
        /// </summary>
        internal static string msgConfirmEmailError {
            get {
                return ResourceManager.GetString("msgConfirmEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password error.
        /// </summary>
        internal static string msgConfirmPasswordError {
            get {
                return ResourceManager.GetString("msgConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format error.
        /// </summary>
        internal static string msgEmailFormatError {
            get {
                return ResourceManager.GetString("msgEmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery added successfully.
        /// </summary>
        internal static string msgGalleryAddedSuccessfully {
            get {
                return ResourceManager.GetString("msgGalleryAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile no..
        /// </summary>
        internal static string msgInvalidMobileNo {
            get {
                return ResourceManager.GetString("msgInvalidMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent Successfully.
        /// </summary>
        internal static string msgMessageSentSuccessfully {
            get {
                return ResourceManager.GetString("msgMessageSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed child id.
        /// </summary>
        internal static string msgMissedChildId {
            get {
                return ResourceManager.GetString("msgMissedChildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed daycare admin id.
        /// </summary>
        internal static string msgMissedDayCareAdminId {
            get {
                return ResourceManager.GetString("msgMissedDayCareAdminId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed parent id.
        /// </summary>
        internal static string msgMissedParentId {
            get {
                return ResourceManager.GetString("msgMissedParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed report id.
        /// </summary>
        internal static string msgMissedReportId {
            get {
                return ResourceManager.GetString("msgMissedReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed sender id.
        /// </summary>
        internal static string msgMissedSenderId {
            get {
                return ResourceManager.GetString("msgMissedSenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed teacher id.
        /// </summary>
        internal static string msgMissedTeacherId {
            get {
                return ResourceManager.GetString("msgMissedTeacherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check internet conncetion.
        /// </summary>
        internal static string msgNoInternetConnection {
            get {
                return ResourceManager.GetString("msgNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect.
        /// </summary>
        internal static string msgOldPasswordInCorrect {
            get {
                return ResourceManager.GetString("msgOldPasswordInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        internal static string msgPasswordChanged {
            get {
                return ResourceManager.GetString("msgPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully.
        /// </summary>
        internal static string msgProfileUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("msgProfileUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report added successfully.
        /// </summary>
        internal static string msgReportAddedSuccessfully {
            get {
                return ResourceManager.GetString("msgReportAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter activation code.
        /// </summary>
        internal static string msgReqActivationCode {
            get {
                return ResourceManager.GetString("msgReqActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select activity type.
        /// </summary>
        internal static string msgReqActivityType {
            get {
                return ResourceManager.GetString("msgReqActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter birth date.
        /// </summary>
        internal static string msgReqBirthDate {
            get {
                return ResourceManager.GetString("msgReqBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter child address.
        /// </summary>
        internal static string msgReqChildAddress {
            get {
                return ResourceManager.GetString("msgReqChildAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select child face.
        /// </summary>
        internal static string msgReqChildFace {
            get {
                return ResourceManager.GetString("msgReqChildFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter child name.
        /// </summary>
        internal static string msgReqChildName {
            get {
                return ResourceManager.GetString("msgReqChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter child National ID.
        /// </summary>
        internal static string msgReqChildNationalId {
            get {
                return ResourceManager.GetString("msgReqChildNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select child relationship.
        /// </summary>
        internal static string msgReqChildRelation {
            get {
                return ResourceManager.GetString("msgReqChildRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select city.
        /// </summary>
        internal static string msgReqCity {
            get {
                return ResourceManager.GetString("msgReqCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter confirm password.
        /// </summary>
        internal static string msgReqConfirmPassword {
            get {
                return ResourceManager.GetString("msgReqConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter sender email.
        /// </summary>
        internal static string msgReqContactEmail {
            get {
                return ResourceManager.GetString("msgReqContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter sender name.
        /// </summary>
        internal static string msgReqContactName {
            get {
                return ResourceManager.GetString("msgReqContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter message subject.
        /// </summary>
        internal static string msgReqContactSubject {
            get {
                return ResourceManager.GetString("msgReqContactSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter message title.
        /// </summary>
        internal static string msgReqContactTitle {
            get {
                return ResourceManager.GetString("msgReqContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select country.
        /// </summary>
        internal static string msgReqCountry {
            get {
                return ResourceManager.GetString("msgReqCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter description.
        /// </summary>
        internal static string msgReqDesc {
            get {
                return ResourceManager.GetString("msgReqDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mobile (Emergency).
        /// </summary>
        internal static string msgReqEmergencyMobile {
            get {
                return ResourceManager.GetString("msgReqEmergencyMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name (Emergency).
        /// </summary>
        internal static string msgReqEmergencyName {
            get {
                return ResourceManager.GetString("msgReqEmergencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select relationship (Emergency).
        /// </summary>
        internal static string msgReqEmergencyRelation {
            get {
                return ResourceManager.GetString("msgReqEmergencyRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter end date.
        /// </summary>
        internal static string msgReqEndDate {
            get {
                return ResourceManager.GetString("msgReqEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter father address.
        /// </summary>
        internal static string msgReqFatherAddress {
            get {
                return ResourceManager.GetString("msgReqFatherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select father Id image.
        /// </summary>
        internal static string msgReqFatherId {
            get {
                return ResourceManager.GetString("msgReqFatherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter father mobile.
        /// </summary>
        internal static string msgReqFatherMobile {
            get {
                return ResourceManager.GetString("msgReqFatherMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter father name.
        /// </summary>
        internal static string msgReqFatherName {
            get {
                return ResourceManager.GetString("msgReqFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter father National ID.
        /// </summary>
        internal static string msgReqFatherNationalId {
            get {
                return ResourceManager.GetString("msgReqFatherNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photo or video for add.
        /// </summary>
        internal static string msgReqGalleryItems {
            get {
                return ResourceManager.GetString("msgReqGalleryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter general notes.
        /// </summary>
        internal static string msgReqGeneralNotes {
            get {
                return ResourceManager.GetString("msgReqGeneralNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter health condition.
        /// </summary>
        internal static string msgReqHealthCondition {
            get {
                return ResourceManager.GetString("msgReqHealthCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select relation (Responsible for Child).
        /// </summary>
        internal static string msgReqHomeRelationId {
            get {
                return ResourceManager.GetString("msgReqHomeRelationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mobile (Responsible for Child).
        /// </summary>
        internal static string msgReqHomeRelationMobile {
            get {
                return ResourceManager.GetString("msgReqHomeRelationMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name (Responsible for Child).
        /// </summary>
        internal static string msgReqHomeRelationName {
            get {
                return ResourceManager.GetString("msgReqHomeRelationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter National ID (Responsible for Child).
        /// </summary>
        internal static string msgReqHomeRelationNationalId {
            get {
                return ResourceManager.GetString("msgReqHomeRelationNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter login data.
        /// </summary>
        internal static string msgReqLoginData {
            get {
                return ResourceManager.GetString("msgReqLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter message.
        /// </summary>
        internal static string msgReqMessage {
            get {
                return ResourceManager.GetString("msgReqMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write message firstly.
        /// </summary>
        internal static string msgReqMessageText {
            get {
                return ResourceManager.GetString("msgReqMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mobile no..
        /// </summary>
        internal static string msgReqMobile {
            get {
                return ResourceManager.GetString("msgReqMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mother address.
        /// </summary>
        internal static string msgReqMotherAddress {
            get {
                return ResourceManager.GetString("msgReqMotherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select mother Id image.
        /// </summary>
        internal static string msgReqMotherId {
            get {
                return ResourceManager.GetString("msgReqMotherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mother mobile.
        /// </summary>
        internal static string msgReqMotherMobile {
            get {
                return ResourceManager.GetString("msgReqMotherMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mother name.
        /// </summary>
        internal static string msgReqMotherName {
            get {
                return ResourceManager.GetString("msgReqMotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mother National ID.
        /// </summary>
        internal static string msgReqMotherNationalId {
            get {
                return ResourceManager.GetString("msgReqMotherNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter National Id.
        /// </summary>
        internal static string msgReqNationalId {
            get {
                return ResourceManager.GetString("msgReqNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new password.
        /// </summary>
        internal static string msgReqNewPassword {
            get {
                return ResourceManager.GetString("msgReqNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select nutrition type.
        /// </summary>
        internal static string msgReqNutritionType {
            get {
                return ResourceManager.GetString("msgReqNutritionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter old password.
        /// </summary>
        internal static string msgReqOldPassword {
            get {
                return ResourceManager.GetString("msgReqOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there must be at least one responsible.
        /// </summary>
        internal static string msgReqOneRelation {
            get {
                return ResourceManager.GetString("msgReqOneRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        internal static string msgReqPassword {
            get {
                return ResourceManager.GetString("msgReqPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter reset code.
        /// </summary>
        internal static string msgReqResetCode {
            get {
                return ResourceManager.GetString("msgReqResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter siblings number.
        /// </summary>
        internal static string msgReqSiblingsNumber {
            get {
                return ResourceManager.GetString("msgReqSiblingsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter start date.
        /// </summary>
        internal static string msgReqStartDate {
            get {
                return ResourceManager.GetString("msgReqStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select time.
        /// </summary>
        internal static string msgReqTime {
            get {
                return ResourceManager.GetString("msgReqTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sent successfully.
        /// </summary>
        internal static string msgRequestSent {
            get {
                return ResourceManager.GetString("msgRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user name.
        /// </summary>
        internal static string msgReqUserName {
            get {
                return ResourceManager.GetString("msgReqUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter what you need to know.
        /// </summary>
        internal static string msgReqWhatToKnow {
            get {
                return ResourceManager.GetString("msgReqWhatToKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend activation code completed.
        /// </summary>
        internal static string msgResendCompleted {
            get {
                return ResourceManager.GetString("msgResendCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select daycare.
        /// </summary>
        internal static string msgSelectDayCare {
            get {
                return ResourceManager.GetString("msgSelectDayCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send new password completed.
        /// </summary>
        internal static string msgSendPasswordCompleted {
            get {
                return ResourceManager.GetString("msgSendPasswordCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send password failed.
        /// </summary>
        internal static string msgSendPasswordError {
            get {
                return ResourceManager.GetString("msgSendPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection error ... try again later.
        /// </summary>
        internal static string msgServerConnectionError {
            get {
                return ResourceManager.GetString("msgServerConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image error.
        /// </summary>
        internal static string msgUploadImageError {
            get {
                return ResourceManager.GetString("msgUploadImageError", resourceCulture);
            }
        }
    }
}
